 input-conf = "~~/input_uosc.conf"
 include = "~~/profiles.conf"
 include = "~~/script-opts.conf"
 use-filedir-conf = yes
#log-file = "~~desktop/mpv.log"

### ———————————————————————— 基础 ————————————————————————

 vo = gpu-next
 gpu-context = d3d11
 hwdec = d3d11va

### ———————————————————————— 功能 ————————————————————————

 idle = yes
 input-ime = no
 input-builtin-bindings = no
 title-bar = no

 hr-seek-framedrop = no
 save-position-on-quit = yes
 watch-later-options = start,vid,aid,sid

 directory-mode = ignore
 keep-open = yes
 autofit-smaller = 50%x50%
 keepaspect-window = no
 hidpi-window-scale = no

 demuxer-max-bytes = 1024MiB
 demuxer-max-back-bytes = 512MiB

 watch-later-dir = "~~/cache/watch_later"
 gpu-shader-cache-dir = "~~/cache/shader"
 icc-cache-dir = "~~/cache/icc"
 
### ———————————————————————— OSD ————————————————————————

 load-stats-overlay = no
 osd-on-seek = msg
 osd-bar-w = 100
 osd-bar-h = 1.5
 osd-bar-align-y = -1
 osd-color = "#ffffff"
 osd-outline-color = "#00AEEC"
 osd-font = 微软雅黑
 osd-fractions = yes
 osd-duration = 2000
 osd-bar = no

### ———————————————————————— 音频 ————————————————————————

 ao = wasapi
 volume = 100
 volume-max = 130
 audio-channels = 5.1,stereo
 audio-file-auto = fuzzy

### ———————————————————————— 视频 ————————————————————————

 video-sync = display-resample
 interpolation = yes
 cscale = bilinear
 scale = bilinear
 dscale = bicubic
 sigmoid-upscaling = no
 correct-downscaling = no
 dither-depth = 10
 deinterlace = auto
 hdr-peak-percentile = 99.99
 autocreate-playlist = same
 directory-mode = ignore
 target-colorspace-hint = yes
 target-colorspace-hint-mode = source

### —————————————————— 脚本 滤镜 着色器 ——————————————————

 osc = no

### ———————————————————————— 字幕 ————————————————————————

 sub-auto = fuzzy
 sub-file-paths = sub;Subs;subtitles
 sub-codepage = GB18030
 slang = chs,sc,zh-cn,chi,zh,zh-tw,cht,zho,ze
 subs-fallback = yes
 sub-hdr-peak = 100
 sub-font = "方正准圆_GBK"
 sub-font-size = 44
 sub-scale-signs = yes
 sub-outline-size = 4
 sub-color = "#ffffff"
 sub-border-color = "#e658af"
 sub-use-margins = yes
 sub-ass-force-margins = yes
 image-subs-hdr-peak = 10000

### ———————————————————————— 截图 ————————————————————————

 screenshot-format = png
 screenshot-jpeg-quality = 100
 screenshot-png-compression = 4
 screenshot-webp-lossless = yes
 screenshot-jxl-distance = 0
 screenshot-tag-colorspace = no
 screenshot-high-bit-depth = no
 screenshot-template = "~~desktop/MPV-%P-N%n"