### —————————————————————— 配置预设组 ——————————————————————

[speed_limit1]
 profile-desc=速度变化下限的控制
 profile-cond=p.speed<0.1
 speed=0.1


[speed_limit2]
 profile-desc=速度变化上限的控制
 profile-cond=p.speed>8
 speed=8


[HDR]
 profile-desc=HDR通用
 profile-cond=get("video-params/primaries", "") == "bt.2020"
 profile-restore=copy
 blend-subtitles=no


[minimized]
 profile-desc=最小化时暂停
 profile-cond=window_minimized and vid and not p["current-tracks/video/albumart"]
 profile-restore=copy-equal
 pause