### —————————————————————— 配置预设组 ——————————————————————

[speed_limit1]
 profile-desc = 速度变化下限的控制
 profile-cond = p.speed<0.1
 speed = 0.1

[speed_limit2]
 profile-desc = 速度变化上限的控制
 profile-cond = p.speed>8
 speed = 8

[save_props_auto]
 profile-desc = 基于进度或时长或视频轨类型的自动保存属性
 profile-cond = p.percent_pos> = 90 or p.duration< = 300 or not vid or p["current-tracks/video/albumart"] or p["current-tracks/video/image"]
 profile-restore = copy
 save-position-on-quit = no

[HDR]
 profile-desc = HDR通用
 profile-cond = p["video-params/sig-peak"]>1
 profile-restore = copy
 blend-subtitles = no
 
[minimized]
 profile-desc = 最小化时暂停
 profile-cond = window_minimized and vid and not p["current-tracks/video/albumart"]
 profile-restore = copy-equal
 pause