### ————————————————————————— 控制台 —————————————————————————

 script-opts-append=console-font_size=16
 script-opts-append=console-border_size=0.9
 script-opts-append=console-monospace_font=微软雅黑

### ———————————————————— 保存全局属性并恢复 ————————————————————

 script-opts-append = save_global_props-props=volume,mute

### —————————————————————— 多功能控制界面 ——————————————————————

 script-opts-append=uosc-video_types=avi,flv,m2ts,m4v,mkv,mov,mp4,mpeg,mpg,ogv,rm,rmvb,ts,vob,webm,wmv
 script-opts-append=uosc-audio_types=aac,ac3,ape,dsf,dts,flac,m4a,mka,mp3,ogg,opus,wav,wma,wv
 script-opts-append=uosc-image_types=apng,avif,bmp,gif,jfif,jpeg,jpg,jxl,png,svg,tif,tiff,webp
 script-opts-append=uosc-subtitle_types=ass,idx,lrc,mks,pgs,sup,srt,ssa,txt,vtt
 script-opts-append=uosc-default_directory={drives}
 script-opts-append=uosc-languages=slang
 